# A TOML plugin for proto:
# https://moonrepo.dev/docs/proto/plugins#toml-plugin

name = "dnscontrol"
type = "cli"

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"

[platform.linux]
download-file = "dnscontrol_{version}_linux_{arch}.tar.gz"

[platform.macos]
download-file = "dnscontrol_{version}_darwin_all.tar.gz"

[platform.windows]
download-file = "dnscontrol_{version}_windows_{arch}.zip"

[install]
download-url = "https://github.com/StackExchange/dnscontrol/releases/download/v{version}/{download_file}"

[resolve]
git-url = "https://github.com/StackExchange/dnscontrol"
