# A TOML plugin for proto:
# https://moonrepo.dev/docs/proto/plugins#toml-plugin

name = "grit"
type = "cli"
description = "GritQL is a query language for searching, linting, and modifying code."


[platform.linux]
download-file = "grit-{arch}-unknown-linux-gnu.tar.gz"
checksum-file = "grit-{arch}-unknown-linux-gnu.tar.gz.sha256"
archive-prefix = "grit-{arch}-unknown-linux-gnu"
exe-path = "grit"

[platform.macos]
download-file = "grit-{arch}-apple-darwin.tar.gz"
checksum-file = "grit-{arch}-apple-darwin.tar.gz.sha256"
archive-prefix = "grit-{arch}-apple-darwin"
exe-path = "grit"

[platform.windows]
download-file = "grit-{arch}-pc-windows-msvc.tar.gz"
checksum-file = "grit-{arch}-pc-windows-msvc.tar.gz.sha256"
archive-prefix = "grit-{arch}-pc-windows"
exe-path = "grit.exe"

[install]
download-url = "https://github.com/getgrit/gritql/releases/download/v{version}/{download_file}"
[resolve]
git-url = "https://github.com/getgrit/gritql"