# A TOML plugin for proto:
# https://moonrepo.dev/docs/proto/plugins#toml-plugin

name = "hurl"
type = "cli"

[platform.linux]
download-file = "hurl-{version}-{arch}-unknown-linux-gnu.tar.gz"
archive-prefix = "hurl-{version}-{arch}-unknown-linux-gnu"

[platform.macos]
download-file = "hurl-{version}-{arch}-apple-darwin.tar.gz"
archive-prefix = "hurl-{version}-{arch}-apple-darwin"

[platform.windows]
download-file = "hurl-{version}-x86_64-pc-windows-msvc.zip"
archive-prefix = "hurl-{version}-x86_64-pc-windows-msvc"

[install]
download-url = "https://github.com/Orange-OpenSource/hurl/releases/download/{version}/{download_file}"

[resolve]
git-url = "https://github.com/Orange-OpenSource/hurl"
