# A TOML plugin for proto:
# https://moonrepo.dev/docs/proto/plugins#toml-plugin

name = "just"
type = "cli"

[platform.linux]
download-file = "just-{version}-{arch}-unknown-linux-musl.tar.gz"
unpack = true

[platform.macos]
download-file = "just-{version}-{arch}-apple-darwin.tar.gz"
unpack = true

[platform.windows]
download-file = "just-{version}-{arch}-pc-windows-msvc.zip"
unpack = true

[install]
download-url = "https://github.com/casey/just/releases/download/{version}/{download_file}"
unpack = true

[resolve]
git-url = "https://github.com/casey/just"