# A TOML plugin for proto:
# https://moonrepo.dev/docs/proto/plugins#toml-plugin

name = "k6"
type = "cli"

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"

[platform.linux]
download-file = "k6-v{version}-linux-{arch}.tar.gz"
archive-prefix = "k6-v{version}-linux-{arch}"
bin-path = "k6"

[platform.macos]
download-file = "k6-v{version}-macos-{arch}.zip"
archive-prefix = "k6-v{version}-macos-{arch}"
bin-path = "k6"

[platform.windows]
download-file = "k6-v{version}-windows-{arch}.zip"
archive-prefix = "k6-v{version}-windows-{arch}"
bin-path = "k6.exe"

[install]
download-url = "https://github.com/grafana/k6/releases/download/v{version}/{download_file}"

[resolve]
git-url = "https://github.com/grafana/k6"
