on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push: 
    branches:
      - main
permissions: write-all
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true
      - name: update proto dependencies
        run: proto outdated --update 
      - run: |
          git config user.name ${{ secrets.GIT_USERNAME }}
          git config user.email ${{ secrets.GIT_EMAIL }}
          git add .prototools
          git commit -m "updates"
          git push
      - name: create pull request
        run: gh pr create -B main --title 'Deps Update' --body 'Created by Github action'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
